'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Activity,Database,Film,RefreshCw,Settings2} from 'lucide-react';
import {get,post} from '@/lib/api';

type ProviderRow={name:string;model:string;status:string;configured:boolean;base_url:string;last_checked:string;last_error:string|null};
const states=['all','queued','running','succeeded','failed','cancelled'];
const stateName:Record<string,string>={all:'全部',queued:'等待',running:'运行中',succeeded:'完成',failed:'失败',cancelled:'已取消'};
const retryable=new Set(['fail_to_fetch_task','NETWORK_ERROR','HTTP_408','HTTP_429','HTTP_500','HTTP_502','HTTP_503','HTTP_504','MEDIA_DOWNLOAD_FAILED','RATE_LIMIT']);
export default function AdminPage(){
 const [overview,setOverview]=useState<any>(null),[providers,setProviders]=useState<ProviderRow[]>([]),[jobs,setJobs]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]),[profiles,setProfiles]=useState<any[]>([]),[config,setConfig]=useState<Record<string,string>>({}),[packages,setPackages]=useState<any[]>([]);
 const [filter,setFilter]=useState('all'),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{try{const [o,p,j,m,r,c,k]=await Promise.all([get('/admin/overview'),get<ProviderRow[]>('/admin/providers'),get<any[]>('/admin/jobs'),get<any[]>('/admin/media'),get<any[]>('/admin/profiles'),get<Record<string,string>>('/admin/config'),get<any[]>('/admin/capability-packages')]);setOverview(o);setProviders(p);setJobs(j);setMedia(m);setProfiles(r);setConfig(c);setPackages(k);setError('');}catch(e:any){setError(e.message)}},[]);
 useEffect(()=>{load();const timer=window.setInterval(load,30000);return()=>window.clearInterval(timer)},[load]);
 async function retry(job:any){setError('');try{await post(`/admin/jobs/${job.id}/technical-retry`,{request_id:crypto.randomUUID()});setNotice('技术重试已提交，使用同一制作方案。');await load()}catch(e:any){setError(e.message)}}
 async function change(key:string,value:string){setError('');try{await post('/admin/config',{key,value});setNotice('运行设置已更新。');await load()}catch(e:any){setError(e.message)}}
 return <main className="admin-page"><header className="admin-top"><div><span className="small-label">AI FILM STUDIO · OPERATIONS</span><h1>运行管理台</h1><p>生产服务、任务与媒体的本地运行状态</p></div><div className="button-row"><Link className="secondary" href="/"><ArrowLeft size={15}/> 返回创作</Link><button className="secondary" onClick={load}><RefreshCw size={15}/> 刷新</button></div></header>
 <p className="admin-auth-note">{overview?.test_mode?'TEST ONLY QA 数据库 · 所有任务与媒体均为测试证据。':'本地管理台尚无正式登录与权限控制；上线前必须补齐。'}</p>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}
 <div className="admin-stats"><div><Activity size={19}/><span>生成任务</span><strong>{overview?.jobs?.total??'—'}</strong></div><div><Film size={19}/><span>失败任务</span><strong>{overview?.jobs?.failed??'—'}</strong></div><div><Database size={19}/><span>受管媒体</span><strong>{overview?.media?.count??'—'}</strong></div><div><Settings2 size={19}/><span>缺失媒体</span><strong>{overview?.media?.missing??'—'}</strong></div></div>
 <section className="panel admin-section"><div className="panel-title"><h2>Provider</h2><span className="muted">只显示配置状态，不返回密钥</span></div><div className="admin-table-wrap"><table><thead><tr><th>服务</th><th>模型</th><th>状态</th><th>已配置</th><th>基础地址</th><th>最近检查 / 错误</th></tr></thead><tbody>{providers.map(p=><tr key={p.name}><td>{p.name}</td><td>{p.model}</td><td><span className="admin-status">{p.status}</span></td><td>{p.configured?'是':'否'}</td><td>{p.base_url}</td><td>{p.last_error||'无记录'}</td></tr>)}</tbody></table></div></section>
 <section className="panel admin-section"><div className="panel-title"><h2>Generation Jobs</h2><label>状态 <select aria-label="任务状态筛选" value={filter} onChange={e=>setFilter(e.target.value)}>{states.map(s=><option key={s} value={s}>{stateName[s]}</option>)}</select></label></div><div className="admin-table-wrap"><table><thead><tr><th>状态</th><th>项目 / Clip</th><th>任务</th><th>上游任务 / 重试链</th><th>错误类别</th><th>媒体</th><th>操作</th></tr></thead><tbody>{jobs.filter(j=>filter==='all'||j.status===filter).map(j=><tr key={j.id}><td>{stateName[j.status]} {j.test_only&&<span className="admin-test">TEST ONLY</span>}</td><td>{j.project_id} / {j.clip_id}</td><td><small>{j.id}<br/>{j.task_id}</small></td><td><small>{j.provider_task_id||'—'}<br/>{j.retry_of?`重试自 ${j.retry_of}`:'首次或创作重生成'}</small></td><td>{j.error_category||'—'}</td><td>{j.media_id||'—'}</td><td>{j.status==='failed'&&retryable.has(j.error_category)&&<button className="secondary small" onClick={()=>retry(j)}>技术重试</button>}</td></tr>)}</tbody></table></div>{!jobs.length&&<p className="muted">还没有生成任务。</p>}</section>
 <section className="panel admin-section"><div className="panel-title"><h2>Media</h2><span className="muted">{overview?.media?.bytes?`${(overview.media.bytes/1024/1024).toFixed(1)} MB`:'0 MB'} 已登记</span></div><div className="admin-table-wrap"><table><thead><tr><th>媒体</th><th>项目</th><th>来源</th><th>大小 / 时长</th><th>校验</th><th>文件</th></tr></thead><tbody>{media.map(m=><tr key={m.id}><td>{m.kind} {m.test_only&&<span className="admin-test">TEST ONLY</span>}<br/><small>{m.id}</small></td><td>{m.project_id||'—'}</td><td>{m.source}</td><td>{(m.size_bytes/1024/1024).toFixed(2)} MB · {m.duration??'—'}s</td><td><small>{m.checksum.slice(0,16)}…</small></td><td>{m.available?'可用':'缺失'}</td></tr>)}</tbody></table></div></section>
 <div className="admin-bottom"><section className="panel admin-section"><div className="panel-title"><h2>Model Profiles</h2><span className="muted">只读版本历史</span></div>{profiles.map(p=><details key={p.id+'-'+p.version} className="advanced"><summary>{p.id} · V{p.version} · {p.status} · {p.source}</summary><pre>{JSON.stringify(p.payload,null,2)}</pre></details>)}</section><section className="panel admin-section"><div className="panel-title"><h2>System Config</h2></div>{Object.entries(config).map(([key,value])=><label key={key} className="admin-config"><span>{key}</span>{key.endsWith('_enabled')?<select value={value} onChange={e=>change(key,e.target.value)}><option value="true">启用</option><option value="false">停用</option></select>:<input type="number" min={key==='poll_seconds'?180:1} max={key==='poll_seconds'?900:3} value={value} onChange={e=>setConfig({...config,[key]:e.target.value})} onBlur={()=>change(key,config[key])}/>}</label>)}<p className="muted">生成查询最短间隔 180 秒；技术重试始终需要显式操作。</p></section></div>
 <section className="panel admin-section"><div className="panel-title"><h2>Capability Packages</h2><span className="muted">未来专业能力库的版本化边界</span></div><p className="muted">{packages.length?`${packages.length} 个已登记能力包`:'尚无能力包；本轮不部署 Agent、Skill 或 Style Pack。'}</p></section>
 </main>;
}
